name: Deploy website to Hostinger
on:
  workflow_dispatch: # Allow manual run from Github
  release: # Run automatically when a new release is published
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Set the same versions as your own to ensure your project
      # build without issues.
      node-version: 20.14.0
      npm-version: 10.8.1
    steps:
      - name: ğŸ—‚ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ”¨ Install and setup npm ${{ env.npm-version }}
        uses: npm/action-setup@v2 
        with:
          version: ${{ env.npm-version }}
      - name: ğŸ”§ Install and setup Node.js ${{ env.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-version }}
          cache: 'npm'

      - name: ğŸ› ï¸ Install dependencies
        run: npm install

      - name: ğŸ› ï¸ Build application 
        run: npm run build

      - name: ğŸ“‚ Sync files with FTP server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21 # Change if necessary
          local-dir: ./dist/ # Change if necessary
